In [2]:
import numpy as np
from liblinear.liblinearutil import train, predict, load_model
from preprocessing import preprocessing
from train import spatial_frequency_feature_fusion

In [6]:
images = []

real = "/Users/Danniel/Downloads/Datasets/Try/real (1).png"
gan = "/Users/Danniel/Downloads/Datasets/Try/gan (1).png"

images.append(gan)
images.append(real)

print(images)

['/Users/Danniel/Downloads/Datasets/Try/gan (1).png', '/Users/Danniel/Downloads/Datasets/Try/real (1).png']


In [7]:
preprocessed_img = [preprocessing(image) for image in images]

fused_features = spatial_frequency_feature_fusion(preprocessed_img)



...

Performing image resizing
...

Applying Gaussian Noise Reduction


Image is already in 512x512



Applying Gaussian Noise Reduction
Performing Feature Extraction
Applying Local Binary Pattern



[[  0   0   0 ...   0   0   0]
 [  0  63  62 ... 251 249   0]
 [  0  62  62 ... 255 255   0]
 ...
 [  0 227 255 ... 240 246   0]
 [  0 225 253 ... 240 240   0]
 [  0   0   0 ...   0   0   0]]

1 out of 2 images
Percentage: 50.0




[[  0   0   0 ...   0   0   0]
 [  0 255  14 ... 243 255   0]
 [  0 255 255 ...  57 224   0]
 ...
 [  0 135 135 ...  62 121   0]
 [  0   7 135 ...  60 120   0]
 [  0   0   0 ...   0   0   0]]

2 out of 2 images
Percentage: 100.0


LBP application finished


Applying DWT to Images



[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0 24 73 ... 71 24  0]
 [ 0  8 24 ... 24  8  0]
 [ 0  0  0 ...  0  0  0]]

1 out of 2 images
Percentage: 50.0




[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0

In [8]:
feature_vector = [i.flatten() for i in fused_features]

In [10]:
model = load_model('faces_updated.model')
plat = load_model('platt scaler/platt_updated.model')

In [59]:
labels = np.array([np.ones(1) if "real" in labels else np.zeros(1) for labels in images])
labels = np.vstack(labels)
true_label = labels.reshape(labels.shape[0])

print(true_label)

[0. 1.]


In [11]:
_, _, svm_scores = predict([], feature_vector, model)
print(svm_scores)
predicted_labels, _, prob_estimates = predict([], svm_scores, plat, '-b 1')

print(predicted_labels)
print(prob_estimates)

Accuracy = 50% (1/2) (classification)
[[-0.9260834376110972], [0.9999999997807169]]
Accuracy = 50% (1/2) (classification)
[0.0, 1.0]
[[0.4786654010877187, 0.5213345989122813], [0.5229510712394038, 0.47704892876059624]]


In [61]:
model1 = train(true_label, feature_vector, '-s 1 -c 1 -B 1 -i faces_old_liblinear.model')

_, _, scores_train = predict([], feature_vector, model1)
print(scores_train)

plat1 = train(true_label, scores_train, '-s 0 -c 1 -B 1 -i platt_scale_validate_faces.model')

predicted_labels_final, _, prob_estimates_final = predict([], scores_train, plat1, '-b 1')

print(predicted_labels_final)
print(prob_estimates_final)

Accuracy = 50% (1/2) (classification)
[[0.9260834376110972], [-0.9999999997807169]]
Accuracy = 50% (1/2) (classification)
[0.0, 1.0]
[[0.6509198817147491, 0.3490801182852509], [0.34146785476025865, 0.6585321452397414]]


In [41]:
result = ["Real" if i == 1.0 else "GAN" for i in predicted_labels_final]

print(result)

['GAN', 'Real']
